apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  selector:
    matchLabels:
      app: checkout-service

  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: checkout-service:1.0.0
          ports:
            - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  labels:
    app: checkout-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      nodePort: 30083
  selector:
    app: checkout-service